-- =====================================================
-- REPARACIÓN COMPLETA DE RELACIONES DE USUARIOS
-- =====================================================
-- Ejecutar en: https://zolffzfbxkgiozfbbjnm.supabase.co
-- Navegar a: SQL Editor
-- Copiar y ejecutar todo este script

-- 1. AGREGAR COLUMNA user_int_id A TODAS LAS TABLAS
-- =====================================================

-- Documents
ALTER TABLE documents 
ADD COLUMN IF NOT EXISTS user_int_id INTEGER;

-- Document Analyses  
ALTER TABLE document_analyses 
ADD COLUMN IF NOT EXISTS user_int_id INTEGER;

-- Analysis Results Basic
ALTER TABLE analysis_results_basic 
ADD COLUMN IF NOT EXISTS user_int_id INTEGER;

-- Analysis Results Advanced
ALTER TABLE analysis_results_advanced 
ADD COLUMN IF NOT EXISTS user_int_id INTEGER;

-- Analysis Results AI
ALTER TABLE analysis_results_ai 
ADD COLUMN IF NOT EXISTS user_int_id INTEGER;

-- AI Model Metrics
ALTER TABLE ai_model_metrics 
ADD COLUMN IF NOT EXISTS user_int_id INTEGER;

-- 2. CREAR TABLA user_configurations SI NO EXISTE
-- =====================================================

CREATE TABLE IF NOT EXISTS user_configurations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_int_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    groq_api_key TEXT,
    chutes_api_key TEXT,
    ocr_settings JSONB DEFAULT '{}',
    ai_preferences JSONB DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(user_int_id)
);

-- 3. CREAR FOREIGN KEY CONSTRAINTS
-- =====================================================

-- Documents -> Users (ignorar error si ya existe)
DO $$
BEGIN
    ALTER TABLE documents
    ADD CONSTRAINT fk_documents_user_int_id
    FOREIGN KEY (user_int_id) REFERENCES users(id) ON DELETE CASCADE;
EXCEPTION
    WHEN duplicate_object THEN
        NULL; -- La constraint ya existe, ignorar
END $$;

-- Document Analyses -> Users
DO $$
BEGIN
    ALTER TABLE document_analyses
    ADD CONSTRAINT fk_document_analyses_user_int_id
    FOREIGN KEY (user_int_id) REFERENCES users(id) ON DELETE CASCADE;
EXCEPTION
    WHEN duplicate_object THEN
        NULL; -- La constraint ya existe, ignorar
END $$;

-- Analysis Results Basic -> Users
DO $$
BEGIN
    ALTER TABLE analysis_results_basic
    ADD CONSTRAINT fk_analysis_results_basic_user_int_id
    FOREIGN KEY (user_int_id) REFERENCES users(id) ON DELETE CASCADE;
EXCEPTION
    WHEN duplicate_object THEN
        NULL; -- La constraint ya existe, ignorar
END $$;

-- Analysis Results Advanced -> Users
DO $$
BEGIN
    ALTER TABLE analysis_results_advanced
    ADD CONSTRAINT fk_analysis_results_advanced_user_int_id
    FOREIGN KEY (user_int_id) REFERENCES users(id) ON DELETE CASCADE;
EXCEPTION
    WHEN duplicate_object THEN
        NULL; -- La constraint ya existe, ignorar
END $$;

-- Analysis Results AI -> Users
DO $$
BEGIN
    ALTER TABLE analysis_results_ai
    ADD CONSTRAINT fk_analysis_results_ai_user_int_id
    FOREIGN KEY (user_int_id) REFERENCES users(id) ON DELETE CASCADE;
EXCEPTION
    WHEN duplicate_object THEN
        NULL; -- La constraint ya existe, ignorar
END $$;

-- AI Model Metrics -> Users
DO $$
BEGIN
    ALTER TABLE ai_model_metrics
    ADD CONSTRAINT fk_ai_model_metrics_user_int_id
    FOREIGN KEY (user_int_id) REFERENCES users(id) ON DELETE CASCADE;
EXCEPTION
    WHEN duplicate_object THEN
        NULL; -- La constraint ya existe, ignorar
END $$;

-- 4. ACTUALIZAR DATOS EXISTENTES (ASIGNAR AL USUARIO CAMILO)
-- =====================================================

-- Asignar documentos existentes al usuario Camilo (ID: 2)
UPDATE documents 
SET user_int_id = 2 
WHERE user_int_id IS NULL;

UPDATE document_analyses 
SET user_int_id = 2 
WHERE user_int_id IS NULL;

UPDATE analysis_results_basic 
SET user_int_id = 2 
WHERE user_int_id IS NULL;

UPDATE analysis_results_advanced 
SET user_int_id = 2 
WHERE user_int_id IS NULL;

UPDATE analysis_results_ai 
SET user_int_id = 2 
WHERE user_int_id IS NULL;

UPDATE ai_model_metrics 
SET user_int_id = 2 
WHERE user_int_id IS NULL;

-- Crear configuración para Camilo si no existe
INSERT INTO user_configurations (user_int_id, groq_api_key, chutes_api_key)
VALUES (2, 'your_groq_api_key_here', 'your_chutes_api_key_here')
ON CONFLICT (user_int_id) DO UPDATE SET
    groq_api_key = EXCLUDED.groq_api_key,
    chutes_api_key = EXCLUDED.chutes_api_key,
    updated_at = NOW();

-- 5. HACER user_int_id NOT NULL (después de actualizar datos)
-- =====================================================

ALTER TABLE documents 
ALTER COLUMN user_int_id SET NOT NULL;

ALTER TABLE document_analyses 
ALTER COLUMN user_int_id SET NOT NULL;

ALTER TABLE analysis_results_basic 
ALTER COLUMN user_int_id SET NOT NULL;

ALTER TABLE analysis_results_advanced 
ALTER COLUMN user_int_id SET NOT NULL;

ALTER TABLE analysis_results_ai 
ALTER COLUMN user_int_id SET NOT NULL;

ALTER TABLE ai_model_metrics 
ALTER COLUMN user_int_id SET NOT NULL;

-- 6. CREAR ÍNDICES PARA MEJORAR RENDIMIENTO
-- =====================================================

CREATE INDEX IF NOT EXISTS idx_documents_user_int_id ON documents(user_int_id);
CREATE INDEX IF NOT EXISTS idx_document_analyses_user_int_id ON document_analyses(user_int_id);
CREATE INDEX IF NOT EXISTS idx_analysis_results_basic_user_int_id ON analysis_results_basic(user_int_id);
CREATE INDEX IF NOT EXISTS idx_analysis_results_advanced_user_int_id ON analysis_results_advanced(user_int_id);
CREATE INDEX IF NOT EXISTS idx_analysis_results_ai_user_int_id ON analysis_results_ai(user_int_id);
CREATE INDEX IF NOT EXISTS idx_ai_model_metrics_user_int_id ON ai_model_metrics(user_int_id);

-- 7. FORZAR REFRESCAR EL SCHEMA CACHE
-- =====================================================

NOTIFY pgrst, 'reload schema';

-- 8. VERIFICACIÓN FINAL
-- =====================================================

-- Verificar que todas las tablas tengan user_int_id
SELECT 
    table_name,
    column_name,
    data_type,
    is_nullable
FROM information_schema.columns 
WHERE table_name IN (
    'documents', 'document_analyses', 'analysis_results_basic', 
    'analysis_results_advanced', 'analysis_results_ai', 'ai_model_metrics'
) 
AND column_name = 'user_int_id' 
ORDER BY table_name;

-- Verificar datos asignados
SELECT 
    'documents' as table_name, 
    COUNT(*) as total_records,
    COUNT(user_int_id) as with_user_int_id
FROM documents
UNION ALL
SELECT 
    'document_analyses' as table_name, 
    COUNT(*) as total_records,
    COUNT(user_int_id) as with_user_int_id
FROM document_analyses
UNION ALL
SELECT 
    'analysis_results_basic' as table_name, 
    COUNT(*) as total_records,
    COUNT(user_int_id) as with_user_int_id
FROM analysis_results_basic;

-- =====================================================
-- FIN DEL SCRIPT
-- =====================================================
-- Después de ejecutar este script:
-- 1. Reinicia el servidor Node.js: npm restart
-- 2. Prueba la aplicación
-- 3. El botón de logout debería funcionar
-- 4. El historial de análisis debería mostrar datos