-- =====================================================
-- VERSIÓN SIMPLIFICADA - REPARACIÓN DE RELACIONES
-- =====================================================
-- Ejecutar en orden, sección por sección si hay errores

-- SECCIÓN 1: Agregar columnas user_int_id
-- =====================================
ALTER TABLE documents ADD COLUMN user_int_id INTEGER;
ALTER TABLE document_analyses ADD COLUMN user_int_id INTEGER;
ALTER TABLE analysis_results_basic ADD COLUMN user_int_id INTEGER;
ALTER TABLE analysis_results_advanced ADD COLUMN user_int_id INTEGER;
ALTER TABLE analysis_results_ai ADD COLUMN user_int_id INTEGER;
ALTER TABLE ai_model_metrics ADD COLUMN user_int_id INTEGER;

-- SECCIÓN 2: Crear tabla user_configurations
-- =====================================
CREATE TABLE IF NOT EXISTS user_configurations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_int_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    groq_api_key TEXT,
    chutes_api_key TEXT,
    ocr_settings JSONB DEFAULT '{}',
    ai_preferences JSONB DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(user_int_id)
);

-- SECCIÓN 3: Asignar datos existentes al usuario Camilo (ID: 2)
-- =====================================
UPDATE documents SET user_int_id = 2 WHERE user_int_id IS NULL;
UPDATE document_analyses SET user_int_id = 2 WHERE user_int_id IS NULL;
UPDATE analysis_results_basic SET user_int_id = 2 WHERE user_int_id IS NULL;
UPDATE analysis_results_advanced SET user_int_id = 2 WHERE user_int_id IS NULL;
UPDATE analysis_results_ai SET user_int_id = 2 WHERE user_int_id IS NULL;
UPDATE ai_model_metrics SET user_int_id = 2 WHERE user_int_id IS NULL;

-- SECCIÓN 4: Crear configuración para Camilo
-- =====================================
INSERT INTO user_configurations (user_int_id, groq_api_key, chutes_api_key)
VALUES (2, 'your_groq_api_key_here', 'your_chutes_api_key_here')
ON CONFLICT (user_int_id) DO UPDATE SET
    groq_api_key = EXCLUDED.groq_api_key,
    chutes_api_key = EXCLUDED.chutes_api_key,
    updated_at = NOW();

-- SECCIÓN 5: Crear índices
-- =====================================
CREATE INDEX IF NOT EXISTS idx_documents_user_int_id ON documents(user_int_id);
CREATE INDEX IF NOT EXISTS idx_document_analyses_user_int_id ON document_analyses(user_int_id);
CREATE INDEX IF NOT EXISTS idx_analysis_results_basic_user_int_id ON analysis_results_basic(user_int_id);
CREATE INDEX IF NOT EXISTS idx_analysis_results_advanced_user_int_id ON analysis_results_advanced(user_int_id);
CREATE INDEX IF NOT EXISTS idx_analysis_results_ai_user_int_id ON analysis_results_ai(user_int_id);
CREATE INDEX IF NOT EXISTS idx_ai_model_metrics_user_int_id ON ai_model_metrics(user_int_id);

-- SECCIÓN 6: Refrescar schema cache
-- =====================================
NOTIFY pgrst, 'reload schema';

-- SECCIÓN 7: Verificación
-- =====================================
SELECT 'Verificación de columnas user_int_id' as info;
SELECT 
    table_name,
    column_name,
    data_type
FROM information_schema.columns 
WHERE table_name IN (
    'documents', 'document_analyses', 'analysis_results_basic', 
    'analysis_results_advanced', 'analysis_results_ai', 'ai_model_metrics'
) 
AND column_name = 'user_int_id' 
ORDER BY table_name;

SELECT 'Verificación de datos asignados' as info;
SELECT 
    'documents' as table_name, 
    COUNT(*) as total_records,
    COUNT(user_int_id) as with_user_int_id
FROM documents
UNION ALL
SELECT 
    'document_analyses' as table_name, 
    COUNT(*) as total_records,
    COUNT(user_int_id) as with_user_int_id
FROM document_analyses
UNION ALL
SELECT 
    'analysis_results_basic' as table_name, 
    COUNT(*) as total_records,
    COUNT(user_int_id) as with_user_int_id
FROM analysis_results_basic;