#!/bin/bash

echo "🔧 Reconstruyendo esquema de base de datos Supabase..."

# Variables de entorno (ajusta según tu configuración)
SUPABASE_URL="https://fvpnfefppfzxdvfhxqjl.supabase.co"
SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2cG5mZWZwcGZ6eGR2Zmh4cWpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM5NjQ4NzIsImV4cCI6MjA0OTU0MDg3Mn0.7tq0S2XwM2Zk_JkXv9a8Y6z3XJhQJJRqj3aF3wKkR4"

echo "🗑️ Eliminando tablas existentes..."

# Eliminar tablas en orden correcto (debido a dependencias)
curl -X POST "${SUPABASE_URL}/rest/v1/rpc/execute_sql" \
  -H "apikey: ${SUPABASE_KEY}" \
  -H "Authorization: Bearer ${SUPABASE_KEY}" \
  -H "Content-Type: application/json" \
  -d '{
    "sql": "DROP TABLE IF EXISTS analysis_metrics CASCADE;"
  }' 2>/dev/null

curl -X POST "${SUPABASE_URL}/rest/v1/rpc/execute_sql" \
  -H "apikey: ${SUPABASE_KEY}" \
  -H "Authorization: Bearer ${SUPABASE_KEY}" \
  -H "Content-Type: application/json" \
  -d '{
    "sql": "DROP TABLE IF EXISTS analysis_results_ai CASCADE;"
  }' 2>/dev/null

curl -X POST "${SUPABASE_URL}/rest/v1/rpc/execute_sql" \
  -H "apikey: ${SUPABASE_KEY}" \
  -H "Authorization: Bearer ${SUPABASE_KEY}" \
  -H "Content-Type: application/json" \
  -d '{
    "sql": "DROP TABLE IF EXISTS analysis_results_advanced CASCADE;"
  }' 2>/dev/null

curl -X POST "${SUPABASE_URL}/rest/v1/rpc/execute_sql" \
  -H "apikey: ${SUPABASE_KEY}" \
  -H "Authorization: Bearer ${SUPABASE_KEY}" \
  -H "Content-Type: application/json" \
  -d '{
    "sql": "DROP TABLE IF EXISTS analysis_results_basic CASCADE;"
  }' 2>/dev/null

curl -X POST "${SUPABASE_URL}/rest/v1/rpc/execute_sql" \
  -H "apikey: ${SUPABASE_KEY}" \
  -H "Authorization: Bearer ${SUPABASE_KEY}" \
  -H "Content-Type: application/json" \
  -d '{
    "sql": "DROP TABLE IF EXISTS document_analyses CASCADE;"
  }' 2>/dev/null

curl -X POST "${SUPABASE_URL}/rest/v1/rpc/execute_sql" \
  -H "apikey: ${SUPABASE_KEY}" \
  -H "Authorization: Bearer ${SUPABASE_KEY}" \
  -H "Content-Type: application/json" \
  -d '{
    "sql": "DROP TABLE IF EXISTS documents CASCADE;"
  }' 2>/dev/null

curl -X POST "${SUPABASE_URL}/rest/v1/rpc/execute_sql" \
  -H "apikey: ${SUPABASE_KEY}" \
  -H "Authorization: Bearer ${SUPABASE_KEY}" \
  -H "Content-Type: application/json" \
  -d '{
    "sql": "DROP TABLE IF EXISTS user_configurations CASCADE;"
  }' 2>/dev/null

echo "📝 Creando tabla users..."

curl -X POST "${SUPABASE_URL}/rest/v1/rpc/execute_sql" \
  -H "apikey: ${SUPABASE_KEY}" \
  -H "Authorization: Bearer ${SUPABASE_KEY}" \
  -H "Content-Type: application/json" \
  -d '{
    "sql": "
      CREATE TABLE IF NOT EXISTS users (
        id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        email VARCHAR(255) UNIQUE NOT NULL,
        username VARCHAR(100) UNIQUE NOT NULL,
        password_hash VARCHAR(255) NOT NULL,
        first_name VARCHAR(100),
        last_name VARCHAR(100),
        role VARCHAR(50) DEFAULT '\''user'\'',
        is_active BOOLEAN DEFAULT true,
        email_verified BOOLEAN DEFAULT false,
        subscription_tier VARCHAR(50) DEFAULT '\''free'\'',
        api_usage_limit INTEGER DEFAULT 100,
        monthly_api_count INTEGER DEFAULT 0,
        storage_quota_mb INTEGER DEFAULT 100,
        storage_used_mb INTEGER DEFAULT 0,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
        last_login TIMESTAMP WITH TIME ZONE
      );
    "
  }' 2>/dev/null

echo "📄 Creando tabla documents..."

curl -X POST "${SUPABASE_URL}/rest/v1/rpc/execute_sql" \
  -H "apikey: ${SUPABASE_KEY}" \
  -H "Authorization: Bearer ${SUPABASE_KEY}" \
  -H "Content-Type: application/json" \
  -d '{
    "sql": "
      CREATE TABLE IF NOT EXISTS documents (
        id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        user_int_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        original_filename VARCHAR(500) NOT NULL,
        file_path VARCHAR(1000),
        file_size_bytes BIGINT,
        file_type VARCHAR(50),
        mime_type VARCHAR(255),
        file_hash VARCHAR(255),
        processing_status VARCHAR(50) DEFAULT '\''pending'\'',
        uploaded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
        metadata JSONB DEFAULT '\''{}'\'',
        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
      );
    "
  }' 2>/dev/null

echo "🔍 Creando tabla document_analyses..."

curl -X POST "${SUPABASE_URL}/rest/v1/rpc/execute_sql" \
  -H "apikey: ${SUPABASE_KEY}" \
  -H "Authorization: Bearer ${SUPABASE_KEY}" \
  -H "Content-Type: application/json" \
  -d '{
    "sql": "
      CREATE TABLE IF NOT EXISTS document_analyses (
        id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        document_id BIGINT NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
        user_int_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        analysis_type VARCHAR(100) DEFAULT '\''document'\'',
        ai_model_used VARCHAR(255),
        ai_strategy VARCHAR(100),
        analysis_config JSONB DEFAULT '\''{}'\'',
        processing_time_ms INTEGER,
        confidence_score DECIMAL(5,4),
        status VARCHAR(50) DEFAULT '\''pending'\'',
        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
        completed_at TIMESTAMP WITH TIME ZONE
      );
    "
  }' 2>/dev/null

echo "📊 Creando tabla analysis_results_basic..."

curl -X POST "${SUPABASE_URL}/rest/v1/rpc/execute_sql" \
  -H "apikey: ${SUPABASE_KEY}" \
  -H "Authorization: Bearer ${SUPABASE_KEY}" \
  -H "Content-Type: application/json" \
  -d '{
    "sql": "
      CREATE TABLE IF NOT EXISTS analysis_results_basic (
        id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        analysis_id BIGINT NOT NULL REFERENCES document_analyses(id) ON DELETE CASCADE,
        page_count INTEGER DEFAULT 0,
        word_count INTEGER DEFAULT 0,
        character_count INTEGER DEFAULT 0,
        language_detected VARCHAR(10) DEFAULT '\''unknown'\'',
        readability_score DECIMAL(5,4) DEFAULT 0,
        document_info JSONB DEFAULT '\''{}'\'',
        statistics JSONB DEFAULT '\''{}'\'',
        content JSONB DEFAULT '\''{}'\'',
        structure JSONB DEFAULT '\''{}'\'',
        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
      );
    "
  }' 2>/dev/null

echo "🧠 Creando tabla analysis_results_advanced..."

curl -X POST "${SUPABASE_URL}/rest/v1/rpc/execute_sql" \
  -H "apikey: ${SUPABASE_KEY}" \
  -H "Authorization: Bearer ${SUPABASE_KEY}" \
  -H "Content-Type: application/json" \
  -d '{
    "sql": "
      CREATE TABLE IF NOT EXISTS analysis_results_advanced (
        id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        analysis_id BIGINT NOT NULL REFERENCES document_analyses(id) ON DELETE CASCADE,
        keywords TEXT[],
        phrases TEXT[],
        entities JSONB DEFAULT '\''{}'\'',
        sentiment_analysis JSONB DEFAULT '\''{}'\'',
        classification JSONB DEFAULT '\''{}'\'',
        advanced_metrics JSONB DEFAULT '\''{}'\'',
        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
      );
    "
  }' 2>/dev/null

echo "🤖 Creando tabla analysis_results_ai..."

curl -X POST "${SUPABASE_URL}/rest/v1/rpc/execute_sql" \
  -H "apikey: ${SUPABASE_KEY}" \
  -H "Authorization: Bearer ${SUPABASE_KEY}" \
  -H "Content-Type: application/json" \
  -d '{
    "sql": "
      CREATE TABLE IF NOT EXISTS analysis_results_ai (
        id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        analysis_id BIGINT NOT NULL REFERENCES document_analyses(id) ON DELETE CASCADE,
        ai_model VARCHAR(255),
        ai_provider VARCHAR(100),
        prompt_used TEXT,
        response_generated TEXT,
        tokens_used INTEGER DEFAULT 0,
        cost_usd DECIMAL(10,6) DEFAULT 0,
        processing_time_ms INTEGER DEFAULT 0,
        quality_metrics JSONB DEFAULT '\''{}'\'',
        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
      );
    "
  }' 2>/dev/null

echo "⚙️ Creando tabla user_configurations..."

curl -X POST "${SUPABASE_URL}/rest/v1/rpc/execute_sql" \
  -H "apikey: ${SUPABASE_KEY}" \
  -H "Authorization: Bearer ${SUPABASE_KEY}" \
  -H "Content-Type: application/json" \
  -d '{
    "sql": "
      CREATE TABLE IF NOT EXISTS user_configurations (
        id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        user_id BIGINT DEFAULT 1,
        groq_api_key TEXT,
        chutes_api_key TEXT,
        ocr_settings JSONB DEFAULT '\''{}'\'',
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
      );
    "
  }' 2>/dev/null

echo "📈 Creando tabla analysis_metrics..."

curl -X POST "${SUPABASE_URL}/rest/v1/rpc/execute_sql" \
  -H "apikey: ${SUPABASE_KEY}" \
  -H "Authorization: Bearer ${SUPABASE_KEY}" \
  -H "Content-Type: application/json" \
  -d '{
    "sql": "
      CREATE TABLE IF NOT EXISTS analysis_metrics (
        id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        analysis_id BIGINT REFERENCES document_analyses(id) ON DELETE SET NULL,
        user_int_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
        model_name VARCHAR(255),
        provider VARCHAR(100),
        document_type VARCHAR(50),
        ocr_confidence INTEGER,
        strategy_used VARCHAR(100),
        parameters JSONB DEFAULT '\''{}'\'',
        success BOOLEAN DEFAULT true,
        response_time_ms INTEGER,
        accuracy_score DECIMAL(5,4),
        cost_usd DECIMAL(10,6) DEFAULT 0,
        tokens_used INTEGER DEFAULT 0,
        session_id VARCHAR(255),
        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
      );
    "
  }' 2>/dev/null

echo "👤 Insertando usuario Camilo Alegria..."

curl -X POST "${SUPABASE_URL}/rest/v1/rpc/execute_sql" \
  -H "apikey: ${SUPABASE_KEY}" \
  -H "Authorization: Bearer ${SUPABASE_KEY}" \
  -H "Content-Type: application/json" \
  -d '{
    "sql": "
      INSERT INTO users (id, email, username, password_hash, first_name, last_name, role, is_active, email_verified)
      VALUES (2, '\''camilo@alegria.com'\'', '\''camilo_alegria'\'', '\''$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewdBPj6ukx.LrUpm'\'', '\''Camilo'\'', '\''Alegria'\'', '\''user'\'', true, false)
      ON CONFLICT (id) DO NOTHING;
    "
  }' 2>/dev/null

echo "🔧 Creando índices..."

curl -X POST "${SUPABASE_URL}/rest/v1/rpc/execute_sql" \
  -H "apikey: ${SUPABASE_KEY}" \
  -H "Authorization: Bearer ${SUPABASE_KEY}" \
  -H "Content-Type: application/json" \
  -d '{
    "sql": "
      CREATE INDEX IF NOT EXISTS idx_documents_user_int_id ON documents(user_int_id);
      CREATE INDEX IF NOT EXISTS idx_documents_status ON documents(processing_status);
      CREATE INDEX IF NOT EXISTS idx_document_analyses_user_int_id ON document_analyses(user_int_id);
      CREATE INDEX IF NOT EXISTS idx_document_analyses_document_id ON document_analyses(document_id);
      CREATE INDEX IF NOT EXISTS idx_analysis_results_basic_analysis_id ON analysis_results_basic(analysis_id);
    "
  }' 2>/dev/null

echo "🧹 Limpiando caché..."

curl -X POST "${SUPABASE_URL}/rest/v1/rpc/execute_sql" \
  -H "apikey: ${SUPABASE_KEY}" \
  -H "Authorization: Bearer ${SUPABASE_KEY}" \
  -H "Content-Type: application/json" \
  -d '{
    "sql": "VACUUM FULL; ANALYZE;"
  }' 2>/dev/null

echo "✅ Esquema reconstruido exitosamente"